# Generated by Django 5.0.6 on 2024-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_birthday_alter_member_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
        ),
    ]
