# Generated by Django 5.0.6 on 2024-07-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department_tag', models.CharField(max_length=255, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=10)),
                ('prereqs', models.CharField(max_length=255, null=True)),
                ('overlap', models.CharField(max_length=255, null=True)),
                ('same_as', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
