# Generated by Django 5.0.6 on 2024-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='units',
        ),
        migrations.AddField(
            model_name='course',
            name='unit_max',
            field=models.CharField(default=4, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unit_min',
            field=models.CharField(default=4, max_length=5),
            preserve_default=False,
        ),
    ]
