# Generated by Django 5.0.6 on 2024-07-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_course_department_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coreq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='restriction',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
