# Generated by Django 5.0.6 on 2024-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
